//! Auto-generated NFSv4 common XDR types with explicit NFSv4.1 extensions.
//!
//! Generated by `fastxdr` from `src/nfs4/xdr/nfs4.x` during `cargo build`.
//! **Do not edit directly.**
//!
//! Re-exports are intentionally broad — many types are used only by specific
//! sub-modules (layout, delegation, state) that may not yet be fully wired in.

#[allow(unused, non_camel_case_types, dead_code, clippy::all, clippy::pedantic)]
mod nfs4_generated {
    include!(concat!(env!("OUT_DIR"), "/nfs4_xdr.rs"));
}

// Only nfsstat4 is used by the current hand-rolled encoder/decoder.
// Other types are re-exported for future use when we migrate to generated decoders.
#[allow(unused_imports)]
pub use nfs4_generated::xdr::{nfsstat4, stateid4};
