from __future__ import annotations

import io
import os
from collections.abc import AsyncIterator, Iterator
from dataclasses import dataclass
from enum import Enum, IntEnum, IntFlag
from typing import Any, NoReturn

__version__: str

class Version(str, Enum):
    def __new__(cls, value: str) -> Version: ...
    NFS_V3 = "3"
    NFS_V4_0 = "4.0"
    NFS_V4_1 = "4.1"

class Lifecycle(str, Enum):
    def __new__(cls, value: str) -> Lifecycle: ...
    READY = "ready"
    CLOSING = "closing"
    CLOSED = "closed"

class FileType(str, Enum):
    def __new__(cls, value: str) -> FileType: ...
    FILE = "file"
    DIRECTORY = "directory"
    SYMLINK = "symlink"
    BLOCK_DEVICE = "block_device"
    CHARACTER_DEVICE = "character_device"
    FIFO = "fifo"
    SOCKET = "socket"
    UNKNOWN = "unknown"

class AceType(IntEnum):
    ALLOW = 0
    DENY = 1
    AUDIT = 2
    ALARM = 3

class AceFlags(IntFlag):
    FILE_INHERIT = 0x01
    DIRECTORY_INHERIT = 0x02
    NO_PROPAGATE_INHERIT = 0x04
    INHERIT_ONLY = 0x08
    SUCCESSFUL_ACCESS = 0x10
    FAILED_ACCESS = 0x20
    IDENTIFIER_GROUP = 0x40
    INHERITED = 0x80

class AceMask(IntFlag):
    READ_DATA = 0x000001
    WRITE_DATA = 0x000002
    APPEND_DATA = 0x000004
    READ_NAMED_ATTRS = 0x000008
    WRITE_NAMED_ATTRS = 0x000010
    EXECUTE = 0x000020
    DELETE_CHILD = 0x000040
    READ_ATTRIBUTES = 0x000080
    WRITE_ATTRIBUTES = 0x000100
    DELETE = 0x010000
    READ_ACL = 0x020000
    WRITE_ACL = 0x040000
    WRITE_OWNER = 0x080000
    SYNCHRONIZE = 0x100000

class Acl41Flags(IntFlag):
    AUTO_INHERIT = 0x01
    PROTECTED = 0x02
    DEFAULTED = 0x04

@dataclass(frozen=True)
class NfsAce:
    type: AceType
    flags: AceFlags
    access_mask: AceMask
    who: str

@dataclass(frozen=True)
class NfsAcl41:
    flags: Acl41Flags
    aces: tuple[NfsAce, ...]

class OperationOutcome(str, Enum):
    def __new__(cls, value: str) -> OperationOutcome: ...
    DEFINITE_FAILURE = "definite_failure"
    SAFE_TO_RETRY = "safe_to_retry"
    UNCERTAIN = "uncertain"

class OperationClass(str, Enum):
    def __new__(cls, value: str) -> OperationClass: ...
    READ_ONLY = "read_only"
    SESSION_CONTROL = "session_control"
    REPLAY_SENSITIVE = "replay_sensitive"

class RecoveryAction(str, Enum):
    def __new__(cls, value: str) -> RecoveryAction: ...
    RETRY = "retry"
    REOPEN = "reopen"
    REMOUNT = "remount"
    VERIFY_THEN_RESUME = "verify_then_resume"
    DO_NOT_RETRY = "do_not_retry"

@dataclass(frozen=True)
class Health:
    lifecycle: Lifecycle
    generation: int
    lease_healthy: bool | None

@dataclass(frozen=True)
class RecoveryEvent:
    operation: str
    path: str | None
    protocol: str
    outcome: OperationOutcome
    recovery_action: RecoveryAction
    completed_bytes: int | None
    message: str

@dataclass(frozen=True)
class FileInfo:
    path: str
    type: FileType
    mode: int
    nlink: int
    uid: int
    gid: int
    size: int
    used: int
    fsid: int
    fileid: int
    atime_ns: int
    mtime_ns: int
    ctime_ns: int
    owner: str | None
    group: str | None

@dataclass(frozen=True)
class DirEntry:
    name: str
    path: str
    info: FileInfo

@dataclass(frozen=True)
class ExportEntry:
    path: str
    groups: tuple[str, ...]

@dataclass(frozen=True)
class FsInfo:
    max_read: int
    preferred_read: int
    read_multiple: int
    max_write: int
    preferred_write: int
    write_multiple: int
    preferred_directory: int
    max_file_size: int
    time_delta_ns: int
    supports_links: bool
    supports_symlinks: bool
    homogeneous: bool
    can_set_time: bool

@dataclass(frozen=True)
class FsStat:
    total_bytes: int
    free_bytes: int
    available_bytes: int
    total_files: int
    free_files: int
    available_files: int
    invariant_seconds: int

@dataclass(frozen=True)
class Capabilities:
    acl: bool
    named_attributes: bool
    locks: bool
    callbacks: bool
    delegation_retention: bool
    pnfs: bool
    session_diagnostics: bool

@dataclass(frozen=True)
class IoLimits:
    max_read: int
    max_write: int

class NfsError(RuntimeError):
    message: str
    operation: str | None
    protocol: str | None
    code: int | None
    code_name: str | None
    recovery_action: RecoveryAction | None
    outcome: OperationOutcome | None
    operation_class: OperationClass | None
    completed_bytes: int | None
    errno: int | None
    filename: str | None
    errors: tuple[NfsError, ...]
    def __init__(
        self, *, message: str, operation: str | None = ..., protocol: str | None = ...,
        code: int | None = ..., code_name: str | None = ...,
        recovery_action: RecoveryAction | str | None = ...,
        outcome: OperationOutcome | str | None = ...,
        operation_class: OperationClass | str | None = ...,
        completed_bytes: int | None = ..., errno: int | None = ...,
        filename: str | None = ..., errors: tuple[NfsError, ...] = ...,
    ) -> None: ...
    def with_context(
        self, *, operation: str | None = ..., protocol: str | None = ...,
        filename: str | None = ...,
    ) -> NfsError: ...

class NfsNotFoundError(FileNotFoundError, NfsError): ...
class NfsAlreadyExistsError(FileExistsError, NfsError): ...
class NfsPermissionError(PermissionError, NfsError): ...
class NfsIsADirectoryError(IsADirectoryError, NfsError): ...
class NfsNotADirectoryError(NotADirectoryError, NfsError): ...
class NfsTimeoutError(TimeoutError, NfsError): ...
class NfsConnectionError(ConnectionError, NfsError): ...
class NfsOSError(OSError, NfsError): ...
class NfsMountError(NfsError): ...
class NfsRpcError(NfsError): ...
class NfsEncodingError(NfsError): ...
class NfsDirectoryEntryError(NfsError): ...
class NfsUnsupportedError(NotImplementedError, NfsError): ...
class NfsInvalidInputError(ValueError, NfsError): ...
class NfsProtocolError(NfsError): ...
class NfsStateLostError(NfsProtocolError): ...
class NfsRetryableError(NfsProtocolError): ...
class NfsOperationOutcomeError(NfsError): ...
class NfsUncertainOutcomeError(NfsOperationOutcomeError): ...
class NfsPositionUncertainError(NfsError): ...
class NfsLostOpenStateError(NfsStateLostError): ...
class NfsClosedResourceError(ValueError, NfsError): ...
class NfsClientClosedError(NfsClosedResourceError): ...
class NfsModeError(io.UnsupportedOperation, NfsError): ...
class NfsFileCloseError(NfsError): ...
class NfsClientCloseError(NfsError): ...

class Client:
    def __init__(self, _private: NoReturn) -> None: ...
    @classmethod
    def connect(
        cls, url: str, *, versions: tuple[str, ...] | list[str] | None = ...,
        uid: int | None = ..., gid: int | None = ..., nfs_port: int | None = ...,
        mount_port: int | None = ..., rsize: int | None = ..., wsize: int | None = ...,
        readdir_buffer: int | tuple[int, int] | None = ..., noresvport: bool | None = ...,
        retain_delegations: bool | None = ..., readahead: int | None = ...,
        writeback: int | None = ..., connect_timeout: float | None = ...,
        operation_timeout: float | None = ..., recovery_event_capacity: int = ...,
    ) -> Client: ...
    @property
    def version(self) -> Version: ...
    @property
    def health(self) -> Health: ...
    @property
    def capabilities(self) -> Capabilities: ...
    @property
    def io_limits(self) -> IoLimits: ...
    @property
    def closed(self) -> bool: ...
    @property
    def dropped_recovery_event_count(self) -> int: ...
    def recovery_events(self) -> tuple[RecoveryEvent, ...]: ...
    def drain_recovery_events(self) -> tuple[RecoveryEvent, ...]: ...
    def close(self) -> None: ...
    def stat(self, path: os.PathLike[str] | str) -> FileInfo: ...
    def exists(self, path: os.PathLike[str] | str) -> bool: ...
    def scandir(self, path: os.PathLike[str] | str = ...) -> Iterator[DirEntry]: ...
    def listdir(self, path: os.PathLike[str] | str = ...) -> list[str]: ...
    def chmod(self, path: os.PathLike[str] | str, mode: int) -> None: ...
    def chown(self, path: os.PathLike[str] | str, uid: int, gid: int) -> None: ...
    def utime(self, path: os.PathLike[str] | str, *, ns: tuple[int, int]) -> None: ...
    def truncate(self, path: os.PathLike[str] | str, size: int) -> None: ...
    def access(self, path: os.PathLike[str] | str, mode: int) -> bool: ...
    def getdacl(self, path: os.PathLike[str] | str) -> NfsAcl41: ...
    def setdacl(self, path: os.PathLike[str] | str, acl: NfsAcl41) -> None: ...
    def getsacl(self, path: os.PathLike[str] | str) -> NfsAcl41: ...
    def setsacl(self, path: os.PathLike[str] | str, acl: NfsAcl41) -> None: ...
    def getxattr(self, path: os.PathLike[str] | str, name: str) -> bytes: ...
    def setxattr(self, path: os.PathLike[str] | str, name: str, value: Any) -> None: ...
    def listxattr(self, path: os.PathLike[str] | str) -> list[str]: ...
    def removexattr(self, path: os.PathLike[str] | str, name: str) -> None: ...
    def fs_info(self) -> FsInfo: ...
    def fs_stat(self) -> FsStat: ...
    def mkdir(
        self, path: os.PathLike[str] | str, mode: int = ..., *, parents: bool = ...,
        exist_ok: bool = ...,
    ) -> None: ...
    def remove(self, path: os.PathLike[str] | str, *, missing_ok: bool = ...) -> None: ...
    def unlink(self, path: os.PathLike[str] | str, *, missing_ok: bool = ...) -> None: ...
    def rmdir(self, path: os.PathLike[str] | str) -> None: ...
    def rename(self, source: os.PathLike[str] | str, destination: os.PathLike[str] | str) -> None: ...
    def link(self, source: os.PathLike[str] | str, destination: os.PathLike[str] | str) -> None: ...
    def symlink(self, target: os.PathLike[str] | str, link_path: os.PathLike[str] | str) -> None: ...
    def readlink(self, path: os.PathLike[str] | str) -> str: ...
    def touch(self, path: os.PathLike[str] | str, *, exist_ok: bool = ...) -> None: ...
    def read_bytes(self, path: os.PathLike[str] | str) -> bytes: ...
    def write_bytes(self, path: os.PathLike[str] | str, data: Any) -> int: ...
    def open(self, path: os.PathLike[str] | str, mode: str = ...) -> File: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, exc_type: object, exc: BaseException | None, traceback: object) -> None: ...

class AsyncClient:
    def __init__(self, _private: NoReturn) -> None: ...
    @classmethod
    async def connect(
        cls, url: str, *, versions: tuple[str, ...] | list[str] | None = ...,
        uid: int | None = ..., gid: int | None = ..., nfs_port: int | None = ...,
        mount_port: int | None = ..., rsize: int | None = ..., wsize: int | None = ...,
        readdir_buffer: int | tuple[int, int] | None = ..., noresvport: bool | None = ...,
        retain_delegations: bool | None = ..., readahead: int | None = ...,
        writeback: int | None = ..., connect_timeout: float | None = ...,
        operation_timeout: float | None = ..., recovery_event_capacity: int = ...,
    ) -> AsyncClient: ...
    @property
    def version(self) -> Version: ...
    @property
    def health(self) -> Health: ...
    @property
    def capabilities(self) -> Capabilities: ...
    @property
    def io_limits(self) -> IoLimits: ...
    @property
    def closed(self) -> bool: ...
    @property
    def dropped_recovery_event_count(self) -> int: ...
    def recovery_events(self) -> tuple[RecoveryEvent, ...]: ...
    def drain_recovery_events(self) -> tuple[RecoveryEvent, ...]: ...
    async def close(self) -> None: ...
    async def stat(self, path: os.PathLike[str] | str) -> FileInfo: ...
    async def exists(self, path: os.PathLike[str] | str) -> bool: ...
    def scandir(self, path: os.PathLike[str] | str = ...) -> AsyncIterator[DirEntry]: ...
    async def listdir(self, path: os.PathLike[str] | str = ...) -> list[str]: ...
    async def chmod(self, path: os.PathLike[str] | str, mode: int) -> None: ...
    async def chown(self, path: os.PathLike[str] | str, uid: int, gid: int) -> None: ...
    async def utime(self, path: os.PathLike[str] | str, *, ns: tuple[int, int]) -> None: ...
    async def truncate(self, path: os.PathLike[str] | str, size: int) -> None: ...
    async def access(self, path: os.PathLike[str] | str, mode: int) -> bool: ...
    async def getdacl(self, path: os.PathLike[str] | str) -> NfsAcl41: ...
    async def setdacl(self, path: os.PathLike[str] | str, acl: NfsAcl41) -> None: ...
    async def getsacl(self, path: os.PathLike[str] | str) -> NfsAcl41: ...
    async def setsacl(self, path: os.PathLike[str] | str, acl: NfsAcl41) -> None: ...
    async def getxattr(self, path: os.PathLike[str] | str, name: str) -> bytes: ...
    async def setxattr(self, path: os.PathLike[str] | str, name: str, value: Any) -> None: ...
    async def listxattr(self, path: os.PathLike[str] | str) -> list[str]: ...
    async def removexattr(self, path: os.PathLike[str] | str, name: str) -> None: ...
    async def fs_info(self) -> FsInfo: ...
    async def fs_stat(self) -> FsStat: ...
    async def mkdir(
        self, path: os.PathLike[str] | str, mode: int = ..., *, parents: bool = ...,
        exist_ok: bool = ...,
    ) -> None: ...
    async def remove(self, path: os.PathLike[str] | str, *, missing_ok: bool = ...) -> None: ...
    async def unlink(self, path: os.PathLike[str] | str, *, missing_ok: bool = ...) -> None: ...
    async def rmdir(self, path: os.PathLike[str] | str) -> None: ...
    async def rename(self, source: os.PathLike[str] | str, destination: os.PathLike[str] | str) -> None: ...
    async def link(self, source: os.PathLike[str] | str, destination: os.PathLike[str] | str) -> None: ...
    async def symlink(self, target: os.PathLike[str] | str, link_path: os.PathLike[str] | str) -> None: ...
    async def readlink(self, path: os.PathLike[str] | str) -> str: ...
    async def touch(self, path: os.PathLike[str] | str, *, exist_ok: bool = ...) -> None: ...
    async def read_bytes(self, path: os.PathLike[str] | str) -> bytes: ...
    async def write_bytes(self, path: os.PathLike[str] | str, data: Any) -> int: ...
    async def open(self, path: os.PathLike[str] | str, mode: str = ...) -> AsyncFile: ...
    async def __aenter__(self) -> AsyncClient: ...
    async def __aexit__(self, exc_type: object, exc: BaseException | None, traceback: object) -> None: ...

class File(io.RawIOBase):
    def __init__(self, _private: NoReturn) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def mode(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def read(self, size: int = ...) -> bytes: ...
    def readinto(self, target: Any) -> int: ...
    def read_at(self, offset: int, size: int = ...) -> bytes: ...
    def readinto_at(self, target: Any, offset: int) -> int: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...
    def tell(self) -> int: ...
    def write(self, data: Any) -> int: ...
    def write_at(self, data: Any, offset: int) -> int: ...
    def truncate(self, size: int | None = ...) -> int: ...
    def flush(self) -> None: ...
    def fileno(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> File: ...
    def __exit__(self, exc_type: object, exc: BaseException | None, traceback: object) -> None: ...

class AsyncFile:
    def __init__(self, _private: NoReturn) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def mode(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    def tell(self) -> int: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    async def read(self, size: int = ...) -> bytes: ...
    async def readinto(self, target: Any) -> int: ...
    async def read_at(self, offset: int, size: int = ...) -> bytes: ...
    async def readinto_at(self, target: Any, offset: int) -> int: ...
    async def seek(self, offset: int, whence: int = ...) -> int: ...
    async def write(self, data: Any) -> int: ...
    async def write_at(self, data: Any, offset: int) -> int: ...
    async def truncate(self, size: int | None = ...) -> int: ...
    async def flush(self) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> AsyncFile: ...
    async def __aexit__(self, exc_type: object, exc: BaseException | None, traceback: object) -> None: ...

def list_exports(
    host: str, *, versions: tuple[str, ...] | list[str] | None = ...,
    uid: int | None = ..., gid: int | None = ..., nfs_port: int | None = ...,
    mount_port: int | None = ..., rsize: int | None = ..., wsize: int | None = ...,
    readdir_buffer: int | tuple[int, int] | None = ..., noresvport: bool | None = ...,
    retain_delegations: bool | None = ..., connect_timeout: float | None = ...,
    operation_timeout: float | None = ..., recovery_event_capacity: int = ...,
) -> tuple[ExportEntry, ...]: ...
async def list_exports_async(
    host: str, *, versions: tuple[str, ...] | list[str] | None = ...,
    uid: int | None = ..., gid: int | None = ..., nfs_port: int | None = ...,
    mount_port: int | None = ..., rsize: int | None = ..., wsize: int | None = ...,
    readdir_buffer: int | tuple[int, int] | None = ..., noresvport: bool | None = ...,
    retain_delegations: bool | None = ..., connect_timeout: float | None = ...,
    operation_timeout: float | None = ..., recovery_event_capacity: int = ...,
) -> tuple[ExportEntry, ...]: ...
