// NFS3 XDR types generated by fastxdr (build.rs), plus hand-written decoders for the
// directory replies (`DirectoryReply`). Response decoding uses TryFrom<Bytes>.

#[allow(unused, non_camel_case_types, dead_code, clippy::all, clippy::pedantic)]
mod nfs_generated {
    include!(concat!(env!("OUT_DIR"), "/nfs_xdr.rs"));
}

#[allow(unused, non_camel_case_types, dead_code, clippy::all, clippy::pedantic)]
mod mount_generated {
    include!(concat!(env!("OUT_DIR"), "/mount_xdr.rs"));
}

use bytes::Bytes;
use nfs_generated::xdr::{
    DeserialiserExt as _, Error as XdrError, cookie3, cookieverf3, fileid3, filename3,
};

// Non-generic response types — re-export directly.
pub(crate) use nfs_generated::xdr::{
    ACCESS3resok, FSINFO3resok, FSSTAT3resok, GETATTR3resok, LINK3resok, PATHCONF3resok,
    REMOVE3resok, RENAME3resok, RMDIR3resok, SETATTR3resok,
};

// Shared types used by response inspection.
pub use nfs_generated::xdr::{fattr3, nfsstat3, nfstime3, post_op_attr};

// Generic response types — concretised with Bytes.
pub(crate) type COMMIT3resok = nfs_generated::xdr::COMMIT3resok<Bytes>;
pub(crate) type CREATE3resok = nfs_generated::xdr::CREATE3resok<Bytes>;
pub(crate) type LOOKUP3resok = nfs_generated::xdr::LOOKUP3resok<Bytes>;
pub(crate) type MKDIR3resok = nfs_generated::xdr::MKDIR3resok<Bytes>;
pub(crate) type READ3resok = nfs_generated::xdr::READ3resok<Bytes>;
pub(crate) type READDIR3resok = DirectoryReply<entry3>;
pub(crate) type READDIRPLUS3resok = DirectoryReply<entryplus3>;
pub(crate) type READLINK3resok = nfs_generated::xdr::READLINK3resok<Bytes>;
pub(crate) type SYMLINK3resok = nfs_generated::xdr::SYMLINK3resok<Bytes>;
pub(crate) type WRITE3resok = nfs_generated::xdr::WRITE3resok<Bytes>;

// Generic helper types used in readdir/readdirplus and response inspection.
// Names are kept lowercase to match XDR spec conventions.
#[allow(non_camel_case_types)]
pub(crate) type entry3 = nfs_generated::xdr::entry3<Bytes>;
#[allow(non_camel_case_types)]
pub(crate) type entryplus3 = nfs_generated::xdr::entryplus3<Bytes>;
#[allow(non_camel_case_types)]
pub(crate) type post_op_fh3 = nfs_generated::xdr::post_op_fh3<Bytes>;

// Write stability enum.
pub(crate) use nfs_generated::xdr::stable_how;

// Mount protocol types.
#[allow(non_camel_case_types)]
pub(crate) type mountres3_ok = mount_generated::xdr::mountres3_ok<Bytes>;
pub use mount_generated::xdr::mountstat3 as mount_mountstat3;

/// A READDIR3resok / READDIRPLUS3resok (RFC 1813 §3.3.16, §3.3.17) with its entries in a `Vec`.
///
/// On the wire the entries are an XDR optional-data linked list (`*nextentry`). The generated
/// decoders follow it recursively, one stack frame per entry, and a boxed list also drops
/// recursively. A reply sized from the server's read limit holds thousands of entries (about
/// 6,000 READDIRPLUS entries per MiB on DXN-2, several times more for READDIR), which
/// overflowed a debug build's stack. These decoders read one entry after another; every
/// entry's `nextentry` is `None`.
#[derive(Debug)]
pub(crate) struct DirectoryReply<E> {
    pub cookieverf: cookieverf3<Bytes>,
    pub reply: DirectoryEntries<E>,
}

/// The entries of one directory reply, in wire order, and whether the directory ended.
#[derive(Debug)]
pub(crate) struct DirectoryEntries<E> {
    pub entries: Vec<E>,
    pub eof: bool,
}

/// Decodes the entries of a directory reply without recursion; `entry` reads one entry's
/// fields up to, but not including, its `nextentry` discriminant.
fn decode_directory_reply<E>(
    v: &mut Bytes,
    mut entry: impl FnMut(&mut Bytes) -> Result<E, XdrError>,
) -> Result<DirectoryReply<E>, XdrError> {
    // The directory's own attributes: decoded to reach the entries, not used.
    post_op_attr::try_from(&mut *v)?;
    let cookieverf = cookieverf3::try_from(&mut *v)?;
    let mut entries = Vec::new();
    loop {
        match v.try_u32()? {
            0 => break,
            1 => entries.push(entry(v)?),
            d => return Err(XdrError::UnknownOptionVariant(d)),
        }
    }
    let eof = v.try_bool()?;
    Ok(DirectoryReply {
        cookieverf,
        reply: DirectoryEntries { entries, eof },
    })
}

impl TryFrom<&mut Bytes> for DirectoryReply<entry3> {
    type Error = XdrError;

    fn try_from(v: &mut Bytes) -> Result<Self, Self::Error> {
        decode_directory_reply(v, |v| {
            Ok(entry3 {
                fileid: fileid3::try_from(&mut *v)?,
                name: filename3::try_from(&mut *v)?,
                cookie: cookie3::try_from(&mut *v)?,
                nextentry: None,
            })
        })
    }
}

impl TryFrom<&mut Bytes> for DirectoryReply<entryplus3> {
    type Error = XdrError;

    fn try_from(v: &mut Bytes) -> Result<Self, Self::Error> {
        decode_directory_reply(v, |v| {
            Ok(entryplus3 {
                fileid: fileid3::try_from(&mut *v)?,
                name: filename3::try_from(&mut *v)?,
                cookie: cookie3::try_from(&mut *v)?,
                name_attributes: post_op_attr::try_from(&mut *v)?,
                name_handle: post_op_fh3::try_from(&mut *v)?,
                nextentry: None,
            })
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A reply of `count` entries named `e<index>` with cookie `index + 1`, attributes and
    /// handles omitted (`plus` adds the two FALSE discriminants READDIRPLUS carries).
    fn reply(count: u32, plus: bool) -> Bytes {
        let mut data = Vec::new();
        data.extend(0u32.to_be_bytes()); // no directory attributes
        data.extend([7; 8]); // cookie verifier
        for index in 0..count {
            data.extend(1u32.to_be_bytes()); // an entry follows
            data.extend(u64::from(index).to_be_bytes());
            let name = format!("e{index}");
            data.extend((name.len() as u32).to_be_bytes());
            data.extend(name.as_bytes());
            data.resize(data.len().next_multiple_of(4), 0);
            data.extend(u64::from(index + 1).to_be_bytes());
            if plus {
                data.extend(0u32.to_be_bytes()); // no attributes
                data.extend(0u32.to_be_bytes()); // no handle
            }
        }
        data.extend(0u32.to_be_bytes()); // no further entry
        data.extend(1u32.to_be_bytes()); // eof
        Bytes::from(data)
    }

    /// A reply sized from a server's read limit holds thousands of entries. Decoding and
    /// dropping it must not use a stack frame per entry: the recursive generated decoder
    /// overflowed here (and a debug build's 2 MiB test thread at about 6,000 READDIRPLUS
    /// entries from a real server).
    #[test]
    fn long_directory_replies_decode_and_drop_on_a_small_stack() {
        const ENTRIES: u32 = 20_000;
        let decoded = std::thread::Builder::new()
            .stack_size(128 * 1024)
            .spawn(|| {
                let plus = READDIRPLUS3resok::try_from(&mut reply(ENTRIES, true)).unwrap();
                let plain = READDIR3resok::try_from(&mut reply(ENTRIES, false)).unwrap();
                let counts = (plus.reply.entries.len(), plain.reply.entries.len());
                let last = plus.reply.entries.last().map(|entry| entry.cookie.0);
                assert!(plus.reply.eof && plain.reply.eof);
                assert_eq!(plus.cookieverf.0.as_ref(), [7; 8]);
                (counts, last)
            })
            .unwrap()
            .join()
            .unwrap();
        assert_eq!(decoded, ((20_000, 20_000), Some(u64::from(ENTRIES))));
    }

    #[test]
    fn directory_replies_keep_wire_order_and_reject_bad_list_markers() {
        let decoded = READDIRPLUS3resok::try_from(&mut reply(3, true)).unwrap();
        let names: Vec<_> = decoded
            .reply
            .entries
            .iter()
            .map(|entry| {
                (
                    entry.cookie.0,
                    entry.name.0.clone(),
                    entry.nextentry.is_none(),
                )
            })
            .collect();
        assert_eq!(
            names,
            [
                (1, Bytes::from_static(b"e0"), true),
                (2, Bytes::from_static(b"e1"), true),
                (3, Bytes::from_static(b"e2"), true),
            ]
        );
        let mut bad = reply(1, false).to_vec();
        bad[12..16].copy_from_slice(&2u32.to_be_bytes());
        assert!(READDIR3resok::try_from(&mut Bytes::from(bad)).is_err());
        let mut truncated = reply(2, true);
        truncated.truncate(truncated.len() - 6);
        assert!(READDIRPLUS3resok::try_from(&mut truncated).is_err());
    }

    /// Decodes every proper prefix of `reply` with `decode`: each must be a decode error.
    fn every_cut_fails<T, E>(reply: &Bytes, decode: impl Fn(&mut Bytes) -> Result<T, E>) {
        for length in 0..reply.len() {
            let mut cut = reply.slice(..length);
            assert!(
                decode(&mut cut).is_err(),
                "a reply cut to {length} of {} bytes decoded",
                reply.len()
            );
        }
    }

    /// A reply that ends inside the XDR padding after a name (`e0` is followed by two zero bytes)
    /// or a handle is a decode error, never a panic: fastxdr 1.0.2's header advanced past the
    /// padding unchecked (`Bytes::advance`, "cannot advance past `remaining`"); build.rs now checks
    /// it.
    #[test]
    fn a_reply_cut_off_anywhere_is_a_decode_error_never_a_panic() {
        every_cut_fails(&reply(3, true), |v| READDIRPLUS3resok::try_from(v));
        every_cut_fails(&reply(3, false), |v| READDIR3resok::try_from(v));

        // LOOKUP3resok: a 5-byte handle (3 bytes of padding), no attributes.
        let mut lookup = Vec::new();
        lookup.extend(5u32.to_be_bytes());
        lookup.extend([9; 5]);
        lookup.extend([0; 3]);
        lookup.extend(0u32.to_be_bytes()); // no object attributes
        lookup.extend(0u32.to_be_bytes()); // no directory attributes
        let lookup = Bytes::from(lookup);
        let decoded = LOOKUP3resok::try_from(&mut lookup.clone()).unwrap();
        assert_eq!(decoded.object.0.as_ref(), [9; 5]);
        every_cut_fails(&lookup, |v| LOOKUP3resok::try_from(v));

        // MOUNT MNT's mountres3_ok: the same handle, then an empty flavor list.
        let mut mounted = Vec::new();
        mounted.extend(5u32.to_be_bytes());
        mounted.extend([9; 5]);
        mounted.extend([0; 3]);
        mounted.extend(0u32.to_be_bytes());
        let mounted = Bytes::from(mounted);
        assert!(mountres3_ok::try_from(&mut mounted.clone()).is_ok());
        every_cut_fails(&mounted, |v| mountres3_ok::try_from(v));
    }
}
